# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.define "vm"
  config.vm.hostname = "vm"

  config.vm.synced_folder "../keating",
    "/home/ubuntu/keating",
    owner: "ubuntu",
    group: "ubuntu"

  config.vm.provision "shell", privileged: false, path: "./initial.sh"

  config.vm.provider :virtualbox do |vb|
    vb.name = "keating"
    vb.cpus = 2
    vb.memory = 1024
  end
end
